### ISSUE TITLE
Equipment not saved on a quay (ticketing equipment, shelter equipment, general sign)

### ISSUE THREAD

**Issue by gregoirefora** [entur/abzu#41]
When we want to add a equipment (ticketing equipment, shelter equipment, general sign) on a quay, it's not saved in the new version. Can you reproduce it ? We investigate on our side

**Comment by seanes** [comment]
Thank you for reporting this!

We are also able to reproduce this (this has previously been reported internally -- and is todo).
The values are saved, but incorrectly extracted from the GraphQL response on the client side, i.e. 
ticketingEquipment (etc) is a list, not an object. 

We will hopefully provide a fix for this shortly.

**Comment by seanes** [comment]
This issue is solved in [latest commit](https://github.com/entur/abzu/commit/503c1e674071dab30e315b144ab10257c9affbf3) for StopPlace, but not quays. It seems to be an issue with Tiamat (I have reported it).

I'll leave this issue open until is fixed, on either sides.
